language: go
go_import_path: github.com/rvflash/awql

go:
  - 1.7.x
  - 1.8.x

before_install:
  - go get -t -v ./...

script:
  - go test -race $(go list ./... | grep -v vendor)

after_success:
  - bash <(curl -s https://codecov.io/bash)